some more deploy stuff and status code adjust

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -6,7 +6,12 @@ python db/create.py
 touch /var/log/celery/log.log
 celery -A api.access.contest worker -l info --loglevel=DEBUG &
 export TESTING=1
-#python test/test_app.py
+python test/test_app.py
+failtest=$?
+if [[ $failtest != 0 ]]; then
+    echo "Test failed!"
+    exit $failtest
+fi
 export TESTING=0
 if [[ "$BUILD" = "prod" ]]; then
     gunicorn --worker-class eventlet -p app.pid -w 3 app:contestplatform -b :9000
diff --git a/scripts/redeploy b/scripts/redeploy
--- a/scripts/redeploy
+++ b/scripts/redeploy
@@ -1,3 +1,9 @@
+#!/bin/sh
+failtest=$?
+if [[ $failtest != 0 ]]; then
+    echo "Test failed!"
+    exit $failtest
+fi
 #redeploy the app without downtime
 # checks if pid file exist since app is being started with pid file
 if [[ -f app.pid ]];then
